name: Testing Big ERP Action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building Docker Compose
        run: docker-compose up -d --build
      - name: Building Application
        run: docker-compose exec -T service npm build
